### ISSUE TITLE
Android version logging everything as non-fatal (even crashes that we expect are fatal)

### ISSUE THREAD

**Issue by phillipmovista** [hansemannn/titanium-crashlytics#51]
We are seeing ‘fatal’ crashes but they’re labeled as ‘non-fatal’ so determining if they’re fatal or not is difficult.

We were having problems catching ANRs, but now that we have the newest version of the module we are still not seeing "Crashes" ever.

Is this a known problem?

**Comment by m1ga** [comment]
That is "on purpose" since we use `recordException` (https://github.com/hansemannn/titanium-crashlytics/issues/38) to create crashes from Ti. That method will generate non-fatal https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=android#log-excepts logs. But it says "in addition" so from my understanding that should still fire "fatal" crashes.
Did that change at some point or was it like this the whole time?

I've udpate the version in #52 (will upload the binary tomorrow) so that's something you could test

**Comment by hansemannn** [comment]
Should I leave this open then for now? Doing some house cleaning here today :)

**Comment by m1ga** [comment]
Yes, would love to hear some feedback from @phillipmovista about the latest version and if it changed at some point

**Comment by phillipmovista** [comment]
Thank you all. We will add this to our backlog to check this out more.

**Comment by hansemannn** [comment]
Can this be closed @phillipmovista?

**Comment by hansemannn** [comment]
I'm fine with keeping it open until validated, no problem!

**Comment by hansemannn** [comment]
This should now be fixed with recent changes - we see both fatal (crash / ANRs) and non-fatals (errors that could be handled gracefully).
